import { poppins } from "../../public/assets/fonts";
import "@/app/styles/globals.css";


export const metadata = {
  title: "CuratED - Curated Education",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
