import { poppins } from "@/assets/fonts";
import "@/app/styles/globals.css";
import NextTopLoader from "@/components/ui/top-loader";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "CuratED - Curated Education",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NextTopLoader />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
