name: Deploy Curated to Vercel

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install sharp for Linux (force correct binary)
        run: npm install --force --platform=linux --arch=x64 sharp
      
      - name: Install remaining dependencies (including optional)
        run: npm install --include=optional
      
      - name: Verify sharp installation
        run: node -e "require('sharp'); console.log('Sharp is working ✅');"

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            DEPLOY_URL=$(npx vercel --yes --token=$VERCEL_TOKEN --prod --confirm)
            npx vercel alias set $DEPLOY_URL devcurated.vercel.app --token=$VERCEL_TOKEN
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            DEPLOY_URL=$(npx vercel --yes --token=$VERCEL_TOKEN --prod --confirm)
            npx vercel alias set $DEPLOY_URL prodcurated.vercel.app --token=$VERCEL_TOKEN
          fi

      - name: Post deployment message
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "Deployed to devcurated.vercel.app"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deployed to prodcurated.vercel.app"
          fi

